export {pages as pages} 
let pages = {
    AF: '', //TODO - Taliban
    AX: 'Parliament_of_Åland',
    AL: 'Parliament_of_Albania',
    DZ: ['Council_of_the_Nation', 'People%27s_National_Assembly'],
    AS: 'American_Samoa_Fono',
    AD: 'General_Council_(Andorra)',
    AO: 'National_Assembly_(Angola)',
    AI: 'House_of_Assembly_(Anguilla)',
    AQ: '', //TODO - Antarctica
    AG: ['Senate_(Antigua_and_Barbuda)','House_of_Representatives_(Antigua_and_Barbuda)'],
    AR: ['Argentine_Senate','Argentine_Chamber_of_Deputies'],
    AM: 'National_Assembly_(Armenia)',
    AW: 'Parliament_of_Aruba',
    AU: ['Australian_Senate', 'Australian_House_of_Representatives'],
    AT: ['National_Council_(Austria)','Federal_Council_(Austria)'],
    AZ: 'National_Assembly_(Azerbaijan)',
    BS: '', //TODO - 2 chambers, 1 page
    BH: ['Consultative_Council_(Bahrain)', 'Council_of_Representatives_(Bahrain)'],
    BD: 'Jatiya_Sangsad',
    BB: ['Senate_of_Barbados', 'House_of_Assembly_of_Barbados'],
    BY: ['Council_of_the_Republic_(Belarus)', 'House_of_Representatives_(Belarus)'],
    BE: ['Senate_(Belgium)', 'Chamber_of_Representatives_(Belgium)'],
    BZ: ['Senate_(Belize)', 'House_of_Representatives_(Belize)'],
    BJ: 'National_Assembly_(Benin)',
    BM: ['Senate_of_Bermuda','House_of_Assembly_of_Bermuda'],
    BT: ['National_Council_(Bhutan)','National_Assembly_(Bhutan)'], //TODO 'non-partisan' appears as 'partisan'
    BO: ['Chamber_of_Senators_(Bolivia)','Chamber_of_Deputies_(Bolivia)'],
    BA: ['House_of_Representatives_of_Bosnia_and_Herzegovina', 'House_of_Peoples_of_Bosnia_and_Herzegovina'], //TODO throws err; groups = null
    BW: 'National_Assembly_(Botswana)',
    BR: ['Federal_Senate_(Brazil)', 'Chamber_of_Deputies_(Brazil)'],
    IO: '', //TODO ???
    VG: '', //TODO ???
    BN: '', //TODO weird situation over in Brunei
    BG: 'National_Assembly_(Bulgaria)',
    BF: 'National_Assembly_of_Burkina_Faso', //TODO throws error; parsed = null
    BI: ['Senate_(Burundi)', 'National_Assembly_(Burundi)'], //TODO senate throws err; groups = null
    KH: ['Senate_(Cambodia)', 'National_Assembly_(Cambodia)'], 
    CM: ['Senate_(Cameroon)', 'National_Assembly_(Cameroon)'], //TODO throws error; parsed = null
    CA: ['Senate_of_Canada','House_of_Commons_of_Canada'],
    CV: 'National_Assembly_(Cabo_Verde)', //TODO throws error; parsed = null
    BQ: '', //TODO ???
    KY: 'Parliament_of_the_Cayman_Islands', 
    CF: 'National_Assembly_(Central_African_Republic)', //TODO there is a senate but no wiki page for it?
    TD: '', //TODO not currently in use following a coup
    CL: ['Senate_of_Chile', 'Chamber_of_Deputies_of_Chile'], //TODO display issues
    CN: 'Standing_Committee_of_the_National_People%27s_Congress', //TODO special page for NPCSC and included on NPC
    CX: '', //TODO point to Australia
    CC: '', //TODO point to Australia
    CO: ['Senate_of_Colombia','Chamber_of_Representatives_of_Colombia'], 
    KM: 'Assembly_of_the_Union_of_the_Comoros',
    CG: 'National_Assembly_(Republic_of_the_Congo)', //TODO senate exists but doesn't list members
    CK: 'Parliament_of_the_Cook_Islands',
    CR: 'Legislative_Assembly_of_Costa_Rica',
    HR: 'Croatian_Parliament',
    CU: 'National_Assembly_of_People%27s_Power',
    CW: 'Parliament_of_Curaçao',
    CY: 'House_of_Representatives_(Cyprus)',
    CZ: ['Chamber_of_Deputies_of_the_Czech_Republic'], //TODO senate breaks the app entirely
    CD: ['Senate_(Democratic_Republic_of_the_Congo)','National_Assembly_(Democratic_Republic_of_the_Congo)'], //TODO some counts weirdness
    DK: 'Folketing',
    DJ: 'National_Assembly_(Djibouti)', //TODO throws error; colors = null
    DM: 'House_of_Assembly_of_Dominica', //TODO subtitles don't show up because they're not bold
    DO: ['Senate_of_the_Dominican_Republic','Chamber_of_Deputies_of_the_Dominican_Republic'], 
    EC: 'National_Assembly_(Ecuador)',
    EG: ['Senate_(Egypt)','House_of_Representatives_(Egypt)'], 
    SV: 'Legislative_Assembly_of_El_Salvador',
    GQ: ['Senate_(Equatorial_Guinea)', 'Chamber_of_Deputies_(Equatorial_Guinea)'],
    ER: 'National_Assembly_(Eritrea)',
    EE: 'Riigikogu', //TODO misplaced subtitles
    ET: 'House_of_Peoples%27_Representatives', //TODO throws error; counts = null - Senate without parties
    FK: 'Legislative_Assembly_of_the_Falkland_Islands', //TODO throws error on slice
    FO: 'Løgting',
    FM: 'Congress_of_the_Federated_States_of_Micronesia', //unseen
    FJ: 'Parliament_of_Fiji',
    FI: 'Parliament_of_Finland', //TODO party without color
    FR: ['Senate_(France)','National_Assembly_(France)'], //TODO extra text
    GF: 'Assembly_of_French_Guiana', //TODO error on filter
    PF: '',
    TF: '',
    GA: '',
    GM: '',
    GE: '',
    DE: 'Bundestag',
    GH: '',
    GI: '',
    GR: '',
    GL: '',
    GD: '',
    GP: '',
    GU: '',
    GT: '',
    GN: '',
    GW: '',
    GY: '',
    HT: '',
    HN: '',
    HK: '',
    HU: '',
    IS: '',
    IN: '',
    ID: '',
    IR: '',
    IQ: '',
    IE: '',
    IM: '',
    IL: '',
    IT: '',
    CI: '',
    JM: '',
    JP: '',
    JE: '',
    JO: '',
    KZ: '',
    KE: '',
    KI: '',
    XK: '',
    KW: '',
    KG: '',
    LA: '',
    LV: '',
    LB: '',
    LS: '',
    LR: '',
    LY: '',
    LI: '',
    LT: '',
    LU: '',
    MO: '',
    MK: '',
    MG: '',
    MW: '',
    MY: '',
    MV: '',
    ML: '',
    MT: '',
    MH: '',
    MQ: '',
    MR: '',
    MU: '',
    YT: '',
    MX: '',
    MD: '',
    MC: '',
    MN: '',
    ME: '',
    MS: '',
    MA: '',
    MZ: '',
    MM: '',
    NA: '',
    NR: '',
    NP: '',
    NL: ['Senate_(Netherlands)','House_of_Representatives_(Netherlands)'],
    NC: '',
    NZ: '',
    NI: '',
    NE: '',
    NG: '',
    NU: '',
    NF: '',
    KP: '',
    MP: '',
    NO: 'Storting',
    OM: '',
    PK: '',
    PW: '',
    PS: '',
    PA: '',
    PG: '',
    PY: '',
    PE: '',
    PH: '',
    PN: '',
    PL: '',
    PT: '',
    PR: '',
    QA: '',
    RE: '',
    RO: '',
    RU: ['Federation_Council_(Russia)', 'State_Duma'],
    RW: '',
    SH: '',
    KN: '',
    LC: '',
    PM: '',
    VC: '',
    WS: '',
    SM: '',
    ST: '',
    SA: '',
    SN: '',
    RS: '',
    SC: '',
    SL: '',
    SG: '',
    SX: '',
    SK: '',
    SI: '',
    SB: '',
    SO: '',
    ZA: '',
    GS: '',
    KR: '',
    SS: '',
    ES: '',
    LK: '',
    SD: '',
    SR: '',
    SJ: '',
    SZ: '',
    SE: '',
    CH: '',
    SY: '',
    TW: '',
    TJ: '',
    TZ: '',
    TH: '',
    TL: '',
    TG: '',
    TK: '',
    TO: '',
    TT: '',
    TN: '',
    TR: '',
    TM: '',
    TC: '',
    TV: '',
    UG: '',
    UA: '',
    AE: '',
    GB: '',
    US: ['United_States_Senate','United_States_House_of_Representatives'],
    UM: '',
    VI: '',
    UY: '',
    UZ: '',
    VU: '',
    VA: '',
    VE: '',
    VN: '',
    WF: '',
    EH: '',
    YE: '',
    ZM: '',
    ZW: ''
  };